# Site
title: 'VIRUS-19'
subtitle: 'This is not an exhibition. This is not a process. This is a situation.'
keywords: 'art, arte, virus, covid'

# URL
url: 'https://virus19.ml'
baseurl: ''
include: ['_pages']

# Build settings
markdown: kramdown
port: 6864
future: false
