# Site
title: 'VIRUS-19'
subtitle: 'This is not an exhibition. This is not a process. This is a situation.'
keywords: 'art, arte, virus, covid'

# URL
url: 'https://lilozone.github.io'
baseurl: '/virus-19'
include: ['_pages']

# Build settings
markdown: kramdown
port: 6864
future: false
